name: workflow.yml
on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test path 1
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v3
      - name: makedir
        run: |
          mkdir test
          cd test
        shell: /usr/bin/bash -e {0}
      - name: Test path 2
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: test
      - name: Test path 3
        run: |
          cd test
          pwd
          ls -a
      - name: Print run number
        run: |
          RUN_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs?branch=$BRANCH_NAME" \
          | jq '.total_count')
          RUN_NUMBER=$((RUN_COUNT + 1))
          echo "BRANCH_RUN_NUMBER=$RUN_NUMBER" >> $GITHUB_ENV
          echo "Branch-specific run number: $RUN_NUMBER"
