name: workflow.yml
on: [push,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test path 1
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v3
      - name: makedir
        run: |
          mkdir test
          cd test
        shell: /usr/bin/bash -e {0}
      - name: Test path 2
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: test
      - name: Test path 3
        run: |
          cd test
          pwd
          ls -a
      - name: Install GitHub CLI
        run: sudo apt-get install -y gh
      - name: Get branch-specific run number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=${GITHUB_REF_NAME}
          REPO=${GITHUB_REPOSITORY}
        # Count workflow runs on this branch
          RUN_NUMBER=$(gh run list --repo $REPO --branch $BRANCH --json databaseId --limit 1000 | jq '. | length')
        # Increment to include current run
          BRANCH_RUN_NUMBER=$((RUN_NUMBER + 1))
          echo "Branch: $BRANCH"
          echo "Branch-specific run number: $BRANCH_RUN_NUMBER"
          echo "branch_run_number=$BRANCH_RUN_NUMBER" >> $GITHUB_OUTPUT
