name: workflow.yml
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test path 1
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v3
      - name: makedir
        run: |
          mkdir test
          cd test
        shell: /usr/bin/bash -e {0}
      - name: Test path 2
        run: |
          pwd
          ls -a
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: test
      - name: Test path 3
        run: |
          cd test
          pwd
          ls -a
